### ISSUE TITLE
Empty Text File

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#13]
There is an empty text file (```instructions.txt```) file in the ```ADALARDUS``` > ```AD00``` > ```AD00=2nd_Vespers``` directory. What is its purpose?

**Comment by juyaolongpaul** [comment]
In my recent commit, the file name is not `instructions.txt` anymore. It is called `__LetterHeader.txt`, you need to download the newest version of the files. All the text file that has a title `xxxHeader` contains Hughes' original encoding which is not the content of the chants, it is probably some descriptive information I think is important to save for the further purpose. 

Occasionally, there is some information between two offices (e.g., Matins and Vespers), so I just create a text file to contain that information just in case. However, since now we have not talked about how to systematically deal with this kind of information, all the methods I use so far is my intuitive ideas, which might not be what you desire. We can talk about this later as needed.
