### ISSUE TITLE
O_virum_nobilem.mei Time Signature

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#18]
Is there a reason why the piece is in 4/4 time, considering that chants are not metered?

**Comment by juyaolongpaul** [comment]
I am not totally sure about this, but it seems like MEI needs to specify a meter, even though the original chants are not metered.

**Comment by ahankinson** [comment]
MEI doesn't require a meter in a piece.

**Comment by juyaolongpaul** [comment]
Sorry, I went into one MEI file, and realized that I actually do not specify the meter, and the reason why it still looks like 4/4 is that I have to use \<measure\> element in order to incorporate <\note\> element (and I put four notes into each measure), etc. So I wonder is there any method to not render the bar line? If not, I have to stuff all the elements into one single measure in order to look "barless".
