### ISSUE TITLE
The score needs to be barless

### ISSUE THREAD

**Issue by juyaolongpaul** [DDMAL/Andrew-Hughes-Chant#35]
The rendered MEI file by Verovio should not display barline.

**Comment by musicnerd** [comment]
Which score? All of them? I opened a random MEI file and see measures. If you don't want measure lines, you'll have to put everything in one measure.

**Comment by juyaolongpaul** [comment]
Yes, Prof. Helsen wants all of them to be barless. I will implement this way soon, thanks!

**Comment by juyaolongpaul** [comment]
I just implemented your way, and now it looks like this:
![screen shot 2017-06-05 at 11 15 50 am](https://cloud.githubusercontent.com/assets/9313094/26790290/27d1a3ea-49e1-11e7-9168-611cda6d24a5.png)

Now the melody is fine, but the lyrics are squished together, and I just asked Verovio team how to do that.

**Comment by musicnerd** [comment]
OK, so this is because since you now have one measure, it of course will extend forever horizontally. This should be fine, as long as you can scroll in verovio, which I think you can.  There should either be an option to 'stretch' the length of the measure, or else you might have to create a system break (which may involve having to artificially create another measure.) If you can't have a system break mid-measure then the first option is the more preferable one.

**Comment by musicnerd** [comment]
Alternatively distance between notes, or "page" size might be something you can specify in the MEI rather than in verovio... perhaps you should look into that?

**Comment by juyaolongpaul** [comment]
Craig Sapp already replied to my question, which solved my problem:

`Add measure@right="invis" to the measure such as:`
`<measure right="invis">`
`    ...`
`</masure>`

Now it looks like this:

![screen shot 2017-06-05 at 3 21 15 pm](https://cloud.githubusercontent.com/assets/9313094/26799219/aff18968-4a02-11e7-8cec-0a78b92a938a.png)
