### ISSUE TITLE
A new line after a phrase

### ISSUE THREAD

**Issue by juyaolongpaul** [DDMAL/Andrew-Hughes-Chant#39]
Prof. Helsen suggests that it will be better if a new line can be created after a phrase, so a phrase can be better displayed this way.

**Comment by musicnerd** [comment]
That doesn't really make any sense. Do you mean a new system? Did you explain to Prof. Helsen that what displays on one line depends on the screen being used to view (and the zoom level?)

**Comment by juyaolongpaul** [comment]
Yes, I explain that to Prof. Helsen, and then Prof. Fujinaga suggested me using `<sb>` to create a new line (yes this will actually just create a blank space depending on the zoom level). After all, I think as long as `<sb>` can create a blank space to indicate a new phrase, it will be good enough.

**Comment by juyaolongpaul** [comment]
Finally, I use `<space>` rather than `<sb>`. Since `<sb>` can only be added under `<measure>`, it is not accurate enough (since the new phrase usually begin within a measure rather than the beginning of a measure). Now it looks like this:

![screen shot 2017-06-14 at 4 28 52 pm](https://user-images.githubusercontent.com/9313094/27153438-70eb8812-511f-11e7-945b-101426c63fef.png)

There is a blank space on the third line, between "tuS" and "In", which indicates a new phrase.

**Comment by ahankinson** [comment]
`<space>` is "A placeholder used to fill an incomplete measure, layer, etc. most often so that the combined duration of the events equals the number of beats in the measure."

Unless you are using it for this purpose, I would suggest that you do not use this element purely for display aesthetics. 

Why not use `<phrase>`?

**Comment by musicnerd** [comment]
Does <phrase> have any associated visual function when it renders in verovio?  The problem is that Dr. Helsen wants new phrases to be visually marked in some way.  We are going to suggest some alternative options to her.  But Yaolong should probably still use <phrase> in the MEI for analysis purposes regardless of the visual effect (or lack thereof).

**Comment by juyaolongpaul** [comment]
Yes, I think I will use `<phrase>` instead, and at the same time, I will tell Prof. Helsen about this.

**Comment by fujinaga** [comment]
This issue is not resolved.
